models/blog.py
from . import ModelMixin
from . import db
from . import timestamp
from . import blgtimestamp
from .user import User


class Blog(db.Model, ModelMixin):
    __tablename__ = 'blogs'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(1000))
    created_time = db.Column(db.Integer)
    updated_time = db.Column(db.Integer)
    user_id = db.Column(db.Integer)
    content = db.Column(db.String(1000))
    title = db.Column(db.String(1000))

    def __init__(self, form):
        self.content = form.get('content', '')
        self.created_time = blgtimestamp()
        self.username = form.get('username', '')
        self.comments = ''
        self.title = form.get('title', '')


    def update(self, form):
        self.content = form.get('content', '')
        self.save()

class BlogComment(db.Model, ModelMixin):
    __tablename__ = 'blogcomments'
    # 下面是字段定义
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.String(1000))
    created_time = db.Column(db.Integer, default=0)
    username = db.Column(db.String(1000))
    # 定义关系
    user_id = db.Column(db.Integer)
    weibo_id = db.Column(db.Integer)

    def __init__(self, form):
        self.content = form.get('content', '')
        self.created_time = timestamp()
        self.username = form.get('username', '')
        self.weibo_id = form.get('weibo_id', '')

    def get_avatar(self):
        a = User.query.filter_by(username=self.username).first()
        if a is None:
            return 'http://icons.iconarchive.com/icons/ph03nyx/super-mario/256/Retro-Mario-icon.png'
        return a.avatar

models/node.py
from . import ModelMixin
from . import db
from . import timestamp
from .user import User


class Node(db.Model, ModelMixin):
    __tablename__ = 'nodes'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(1000))
    description = db.Column(db.String(1000))
    # has relationship with topic
    topics = db.relationship('Topic', backref="node")
    username = db.Column(db.String(1000))

    def __init__(self, form):
        self.name = form.get('name', '')
        self.username = form.get('username', '')

    def get_avatar(self):
        a = User.query.filter_by(username=self.username).first()
        if a is None:
            return 'http://icons.iconarchive.com/icons/ph03nyx/super-mario/256/Retro-Mario-icon.png'
        return a.avatar

models/topic.py
from . import ModelMixin
from . import db
from . import timestamp
from .user import User

class TopicComment(db.Model, ModelMixin):
    __tablename__ = 'topiccomments'
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.String(1000))
    created_time = db.Column(db.Integer, default=timestamp())
    updated_time = db.Column(db.Integer, default=timestamp())
    user_id = db.Column(db.Integer)
    topic_id = db.Column(db.Integer, db.ForeignKey('topics.id'))
    username = db.Column(db.String(1000))

    def __init__(self, form):
        print('comment init', form)
        self.content = form.get('content', '')
        self.created_time = timestamp()
        self.username = form.get('username', '')
        self.topic_id = form.get('topic_id', '')

    def get_avatar(self):
        a = User.query.filter_by(username=self.username).first()
        if a is None:
            return 'http://icons.iconarchive.com/icons/ph03nyx/super-mario/256/Retro-Mario-icon.png'
        return a.avatar

class Topic(db.Model, ModelMixin):
    __tablename__ = 'topics'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(1000))
    content = db.Column(db.String(1000))
    user_id = db.Column(db.Integer)
    created_time = db.Column(db.Integer, default=timestamp())
    updated_time = db.Column(db.Integer, default=timestamp())
    node_id = db.Column(db.Integer, db.ForeignKey('nodes.id'))
    username = db.Column(db.String(1000))

    def __init__(self, form):
        print('topic init', form)
        self.title = form.get('title', '')
        self.content = form.get('content', '')
        self.username = form.get('username', '')
        self.comments = ''

    def update(self, form):
        print('topic update', form)
        self.title = form.get('title', '')
        self.content = form.get('content', '')
        self.updated_time = timestamp()
        self.save()

    def get_avatar(self):
        a = User.query.filter_by(username=self.username).first()
        if a is None:
            return 'http://icons.iconarchive.com/icons/ph03nyx/super-mario/256/Retro-Mario-icon.png'
        return a.avatar

    def load_comments(self):
        cs = TopicComment.query.filter_by(topic_id=self.id).all()
        return cs

routes/blog.py
from models.blog import Blog
from models.user import User

from routes import *

# for decorators
from functools import wraps


main = Blueprint('blog', __name__)

Model = Blog


# def admin_required(f):
#     @wraps(f)
#     def function(*args, **kwargs):
#         # your code
#         print('admin required')
#         if request.args.get('uid') != '1':
#             print('not admin')
#             abort(404)
#         return f(*args, **kwargs)
#     return function

def current_user():
    uid = session.get('user_id')
    if uid is not None:
        u = User.query.get(uid)
        return u

@main.route('/')
def index():
    u = current_user()
    if u is None:
        return redirect(url_for('user.login_view'))
    bl = Blog.query.order_by(Blog.id.desc()).all()
    for i in bl:
        i.content = markdown(i.content)
    return render_template('blog_index.html', blogs=bl, user=u)


@main.route('/<int:id>')
def show(id):
    m = Model.query.get(id)
    m.content = markdown(m.content)
    print(m.content)
    return render_template('blog.html', blog=m)


@main.route('/add_article')
# @admin_required
def add_article():
    return render_template('blog_add.html')


@main.route('/add', methods=['POST'])
# @admin_required
def add():
    u = current_user()
    if u is not None:
        print('blog add', u.id, u.username)
        form = request.form
        b = Blog(form)
        b.username = u.username
        b.user_id = u.id
        b.save()
        print(b, b.user_id, b.save())
        return redirect(url_for('.index'))
    else:
        abort(401)


@main.route('/update/<int:id>', methods=['POST'])
def update(id):
    form = request.form
    t = Model.query.get(id)
    t.update(form)
    return redirect(url_for('.index'))


@main.route('/delete/<int:id>')
# @admin_required
def delete(id):
    u = current_user()
    b = Model.query.get(id)
    if u.id == b.user_id:
        b.delete()
        return redirect(url_for('.index'))
    else:
        print('删除失败', u.id, b.user_id)
        return redirect(url_for('.index'))

routes/node.py
from models.node import Node
from models.user import User
from models.topic import Topic
from routes import *

# for decorators
from functools import wraps


main = Blueprint('node', __name__)

Model = Node

#
# def admin_required(f):
#     @wraps(f)
#     def function(*args, **kwargs):
#         # your code
#         print('admin required')
#         if request.args.get('uid') != '1':
#             print('not admin')
#             abort(404)
#         return f(*args, **kwargs)
#     return function

def current_user():
    uid = session.get('user_id')
    if uid is not None:
        u = User.query.get(uid)
        return u

@main.route('/new_node')
def index():
    ms = Model.query.all()
    return render_template('node_index.html', node_list=ms)

@main.route('/show')
def node_show(id=4):
    u = current_user()
    if u is None:
        return redirect(url_for('user.login_view'))
    m = Model.query.get(id)
    ms = Node.query.order_by(Node.id.desc()).all()
    t = Topic.query.order_by(Topic.id.desc()).all()
    for i in t:
        i.avatar = i.get_avatar()
    return render_template('node.html', node=m, node_list=ms, topic=t, user=u)

@main.route('/add_topic')
# @admin_required
def add_topic():
    ms = Node.query.order_by(Node.id.desc()).all()
    print(ms)
    return render_template('topic_add.html', node_list=ms)

@main.route('/<int:id>')
def show(id):
    u = current_user()
    if u is None:
        return redirect(url_for('user.login_view'))
    m = Model.query.get(id)
    ms = Node.query.order_by(Node.id.desc()).all()
    t = Topic.query.order_by(Topic.id.desc()).all()
    for i in t:
        i.avatar = i.get_avatar()
    return render_template('node.html', node=m, node_list=ms, topic=t, user=u)


@main.route('/edit/<id>')
# @admin_required
def edit(id):
    t = Model.query.get(id)
    return render_template('node_edit.html', todo=t)


@main.route('/add', methods=['POST'])
# @admin_required
def add():
    form = request.form
    m = Model(form)
    m.save()
    return redirect(url_for('.index'))


@main.route('/update/<int:id>', methods=['POST'])
def update(id):
    form = request.form
    t = Model.query.get(id)
    t.update(form)
    return redirect(url_for('.index'))


@main.route('/delete/<int:id>')
# @admin_required
def delete(id):
    t = Model.query.get(id)
    t.delete()
    return redirect(url_for('.index'))

routes/topic.py
from models.topic import Topic
from models.user import User
from models.topic import TopicComment
from routes import *


main = Blueprint('topic', __name__)

Model = Topic

def current_user():
    uid = session.get('user_id')
    if uid is not None:
        u = User.query.get(uid)
        return u

@main.route('/')
def index():
    ms = Model.query.all()
    return render_template('topic_index.html', node_list=ms)


@main.route('/<int:id>')
def show(id):
    u = current_user()
    m = Model.query.get(id)
    ms = Topic.query.order_by(Topic.id.desc()).all()
    m.content = markdown(m.content)
    for i in ms:
        i.comment = i.load_comments()
        for o in i.comment:
            o.avatar = o.get_avatar()
        i.avatar = i.get_avatar()
        # print(i.comment)
    return render_template('topic.html', topic=m, user=u)


@main.route('/edit/<id>')
def edit(id):
    t = Model.query.get(id)
    return render_template('topic_edit.html', todo=t)


@main.route('/add', methods=['POST'])
def add():
    u = current_user()
    if u is not None:
        form = request.form
        m = Model(form)
        m.node_id = int(form.get('node_id'))
        m.username = u.username
        m.user_id = u.id
        m.save()
        print("save", m.user_id)
        return redirect(url_for('node.show', id=m.node_id))
    else:
        abort(401)

@main.route('/comment', methods=['POST'])
def comment_add():
    u = current_user()
    if u is not None:
        print('comment_add', u.id, u.username)
        form = request.form
        c = TopicComment(form)
        c.user_id = u.id
        c.username = u.username
        c.topic_id = int(form.get('topic_id', -1))
        c.save()
        return redirect(url_for('.show', id=c.topic_id))
    else:
        abort(401)

@main.route('/update/<int:id>', methods=['POST'])
def update(id):
    form = request.form
    t = Model.query.get(id)
    t.update(form)
    return redirect(url_for('.index'))


@main.route('/delete/<int:id>')
def delete(id):
    t = Model.query.get(id)
    t.delete()
    return redirect(url_for('.index'))

templates/base.html
<!doctype html>
<html>
  <head>
    <title>
        {% block title %}{% endblock %} - Tokayaの駅
    </title>
    {% block head %}
        <script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script>
        <script>
            console.log('父模板的 log')
        </script>
        <link rel="shortcut icon" href="/static/img/favicon.ico"/>
        <link rel="bookmark" href="/static/img/favicon.ico"/>
    {% endblock %}
    <link rel="stylesheet" href="/static/css/base.css">
  </head>
<body>
  <div class="container">
      <div class="tokaya-header">
          <div class="tokaya-top-inner">
              <a href="/index" class="tokaya-title">Tokaya の </a>
              <a href="/index" class="tokaya-title tokaya-eki">駅</a>
              <span class="link">
                  <a class="tokaya-nav-item" href="/weibo">微博</a>
                  <a class="tokaya-nav-item" href="/blog">博客</a>
                  <a class="tokaya-nav-item" href="/node/show">论坛</a>
                  <span class="tokaya-dropdown">
                      <a class="tokaya-dropdown-title tokaya-nav-item" href="#">练习</a>
                      <span class="tokaya-dropdown-content">
                          <a class="tokaya-nav-item" href="/todo">todo</a>
                          <a class="tokaya-nav-item" href="/css_practice">css练习</a>
                          <a class="tokaya-nav-item" href="#">关于</a>
                      </span>
                  </span>
                  <a class="tokaya-nav-item" href="/profile">个人资料</a>
                  <a class="tokaya-nav-item" href="/logout">退出</a>
                  <!-- <a class="tokaya-nav-item" href="/profile"> -->
                      <!-- <img src="" alt="" /> -->
                  <!-- </a> -->
              </span>
          </div>
      </div>
      <div class="body">
      {% block content %}

      {% endblock %}
      </div>
      <!-- <div class="tokaya-header footer">
        {% block footer %}
            <span class=""></span>Copyright 2016 by <a href="/">@Tokaya</a>.
        {% endblock %}
      </div> -->
  </div>
</body>
</html>

templates/blog_add.html
{% extends "base.html" %}
{% block head %}
  {{ super() }}
  <link rel="stylesheet" href="/static/css/blog_add.css">
{% endblock %}
{% block title %}主页{% endblock %}
{% block content %}
<div class="tokaya-blog">
    <form action="{{ url_for('.add') }}" method="post">
        <input type="text" name="title" placeholder="文章名字">
        <button>发表</button>
        <a href="{{ url_for('.index') }}">取消编辑</a>
        <div class="tokaya-blog-edit">
            <textarea name="content" placeholder="博文内容"></textarea>
        </div>
    </form>
</div>

{% endblock %}

templates/blog_index.html
{% extends "base.html" %}
{% block head %}
  {{ super() }}
  <link rel="stylesheet" href="/static/css/blog_index.css">
{% endblock %}
{% block title %}博客{% endblock %}
{% block content %}
    <div class="tokaya-blog">
        <div class="tokaya-blog-content">
            {% for b in blogs  %}
                <div class="tokaya-blog-article">
                    <a class="tokaya-blog-title" href="#"><h1>{{ b.title }}</h1></a>
                    <div class="tokaya-blog-username ">
                        {{ b.username }}
                    </div>
                    <div class="tokaya-blog-time">
                        {{ b.created_time }}
                    </div>
                    {{ b.content|safe }}
                    <a class="tokaya-blog-delete" href="{{ url_for('.delete', id=b.id) }}">删除</a>
                </div>
            {% endfor %}
        </div>
        <div class="tokaya-blog-sidebar">
            <div class="tokaya-blog-sidebar-about">
                <div class="tokaya-sidebar-about">
                    About Me
                    <img src="/static/img/tokaya.jpg">
                    <div class="tokaya-sidebar-content">
                        这是自我介绍
                    </div>
                </div>
            </div>
            <div class="tokaya-blog-sidebar-about">
                <div class="tokaya-sidebar-about">
                    Social

                </div>
            </div>
            <div class="tokaya-blog-sidebar-about">
                <a class="tokaya-blog-new" href="{{ url_for('.add_article') }}">新文章</a>
            </div>
        </div>
    </div>

{% endblock %}

templates/css_practice.html
{% extends "base.html" %}
  {% block head %}
    {{ super() }}
    <style>
      .header {
        width: 1024px;
        height: 412px;
        margin: 0 auto;
      }
      .top-img {
        position: absolute;
      }
      .top {
        width: 90%;
        display: flex;
        position: relative;
        margin: 0 auto;
      }
      .searcher {
        width: 95%;
        margin: 20px auto;
        display: flex;
        background-color: #222222;
        border-radius: 4px;
      }
      .search {
        width: 89%;
        background-color: #222222;
        color: white;
        border: 0px solid;
        font-weight: bold;
        font-family: Comic Sans MS;
      }
      .login {
        background-color: black;
        padding: 10px;
      }
      .register {
        color: gray;
        padding: 10px;
      }
      .top-font {
        font-family: 造字工房悦黑（非商用）常规体;
        color: white;
        font-size: 12px;
      }
      .top-inner {
        position: relative;
        margin-top: 230px;
        text-align: center;
      }
      .develop {
        font-size: 18px;
        margin-bottom: 5px;
      }
      .join {
        width: 6%;
        margin: 10px auto 28px auto;;
        padding: 5px;
        background-color: #428AC9;
        border-radius: 4px;
      }
      .tools {
        margin: 0 auto;
        display: flex;
        padding-bottom: 50px;
        border-bottom: 1px solid #EEE;
      }
      .tools-item {
        width: 30%;
        margin: 30px 0px 0 25px;
        text-align: center;

      }
      .tools-img {
        width: 50%;
        height: 50%;
        border-radius: 50%;
        position: relative;
      }
      .tool-font {
        font-family: 造字工房悦黑（非商用）常规体;
        font-size: 12px;
        color: gray;
      }
      .too-item-font {
        font-size: 25px;
        font-weight: bold;
        margin-bottom: 5px;
      }
      .sass-img {
        width: 153px;
        height: 153px;
        margin-bottom: 16px;
      }
      .ruby-img {
        width: 153px;
        height: 153px;
        margin-bottom: 16px;
        display: flex;
        margin-left: 75px;
      }
      .css-img {
        width: 153px;
        height: 155x;
      }
      .body-font {
        margin-top: 115px;
        font-family: 造字工房悦黑（非商用）常规体;
        font-size: 40px;
      }
      .body-item {
        margin: 55px 0px 0 80px;
        display:flex;
        padding-bottom: 50px;
        border-bottom: 1px solid #EEE;
      }
      .mac-img {
        width: 37%;
        height: 30%;
        margin-left: 35px;
        margin-right: 35px;
      }
      .bot {
        padding-top: 40px;
        border-bottom: 1px solid #EEE;
      }
      .bot-font {
        color: gray;
      }
      .left {
        float: left;
      }
      .right {
        float: right;
      }
      .practice-body {
        margin: 15px auto;
        background-color: white;
        padding: 10px 10px 1611px;
      }
    </style>
  {% endblock %}
  {% block title %}HACKSCHOO{% endblock %}
  {% block content %}
  <div class="practice-body">
      <div class="header">
        <img class="top-img" src="{{ url_for('static', filename='img/header.png') }}">
          <div class="top">
            <div class="searcher">
              <input type="text" class="search" name="search" value="HACKSCHOOL">
              <div class="login top-font">
                登陆
              </div>
              <div class="register top-font">
                注册
              </div>
            </div>
          </div>
          <div class="top-inner">
            <div class="develop top-font">
              全栈开发
            </div>
            <div class="top-font">
              8周密集训练前端丶后端技能 ·
            </div>
            <div class="top-font join">
              加入我们
            </div>
          </div>
        <div class="tools">
          <div class="tools-item">
            <img class="tools-img ruby-img" src="{{ url_for('static', filename='img/ruby.png') }}">
            <div class="tool-font too-item-font">
              Ruby on Rails
            </div>
            <div class="tool-font">
              最快速高效地开发产品 丶
            </div>
          </div>
          <div class="tools-item">
            <img class="tools-img css-img" src="{{ url_for('static', filename='img/css.png') }}">
            <div class="tool-font too-item-font">
              CSS
            </div>
            <div class="tool-font">
              精美样式布局·打磨拥有成就感的产品 丶
            </div>
          </div>
          <div class="tools-item">
            <img class="tools-img sass-img" src="{{ url_for('static', filename='img/sass.png') }}">
            <div class="tool-font too-item-font">
              Sass
            </div>
            <div class="tool-font">
              从0到1做出属于自己的Sass产品 丶
            </div>
          </div>
        </div>
        <div class="body">
          <div class="body-item">
            <p class="body-font">
              Rails 环境配置·迅速开始·
            </p>
            <img class="mac-img" src="{{ url_for('static', filename='img/mac.png') }}">
          </div>
          <div class="body-item">
            <img class="mac-img" src="{{ url_for('static', filename='img/rubyw.png') }}">
            <p class="body-font">
              Rails 初级教程·上手开发·
            </p>
          </div>
          <div class="body-item">
            <p class="body-font">
              Rails 中级教程·快速进阶·
            </p>
            <img class="mac-img" src="{{ url_for('static', filename='img/mact.jpg') }}">
          </div>
        </div>
        <div class="bot">
          <span class="top-font bot-font left">
            @2016 HACKSCHOOL
          </span>
          <span class="top-font bot-font right">
            Back to top
          </span>
        </div>
      </div>
  </div>
  {% endblock %}

templates/home.html
{% extends "home_base.html" %}
{% block head %}
  {{ super() }}
  <style type="text/css">
    .tokaya-home-body {
        margin-top: 867px;
    }
  </style>
{% endblock %}
{% block title %}主页{% endblock %}
{% block content %}
    <div class="tokaya-home-body">

    </div>
{% endblock %}

templates/home_base.html
<!doctype html>
<html>
  <head>
    <title>
        {% block title %}{% endblock %} - Tokayaの駅
    </title>
    {% block head %}
        <script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script>
        <script>
            console.log('父模板的 log')
        </script>
    {% endblock %}
    <link rel="stylesheet" href="/static/css/home_base.css">
  </head>
<body>
  <div class="container">
      <div class="tokaya-header">
          <div class="tokaya-top-inner">
              <a href="/" class="tokaya-title">Tokaya の </a>
              <a href="/" class="tokaya-title tokaya-eki">駅</a>
              <span class="link">
                  <a class="tokaya-nav-item" href="/login">登陆</a>
              </span>
          </div>
      </div>
      <div class="body">
      {% block content %}

      {% endblock %}
      </div>
      <div class="tokaya-header footer">
        {% block footer %}
            <span class=""></span>Copyright 2016 by <a href="/">@Tokaya</a>.
        {% endblock %}
      </div>
  </div>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block head %}
  {{ super() }}
  <style type="text/css">
    .tokaya-home-body {
        margin-top: 864px;
    }
  </style>
{% endblock %}
{% block title %}主页{% endblock %}
{% block content %}
    <div class="tokaya-home-body">

    </div>
{% endblock %}

templates/node_show.html
{% extends "base.html" %}
{% block head %}
  {{ super() }}
  <link rel="stylesheet" href="/static/css/node_show.css">
{% endblock %}
{% block title %}论坛{% endblock %}
{% block content %}
    <div class="tokaya-node-container">
        <div class="tokaya-node-content">
            <div class="tokaya-node-title-link">
                {% for n in node_list %}
                    <div class="tokaya-node-title">
                        <a href="{{ url_for('.show', id=n.id) }}">{{ n.name }}</a>
                    </div>
                {% endfor %}
            </div>
            <div class="tokaya-node-topic-cell">
                {% for t in topic %}
                <div class="tokaya-node-topic-block">
                    <a href="/profile">
                        <img class="tokaya-node-topic-avatar" src="{{ t.avatar }}">
                    </a>
                    <div class="tokaya-node-topic-show">
                        <a class="tokaya-node-topic-title" href="{{ url_for('topic.show', id=t.id) }}">
                            {{ t.title }}
                        </a>
                        <div class="tokaya-node-topic-detail">
                            <a class="tokaya-node-topic-tag" href="#">tag</a>
                            <strong>•</strong>
                            <a style="color:#778087;" href="/profile"><strong>{{ t.username }}</strong></a>
                            <strong>•</strong>
                            {{ t.created_time }}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="tokaya-node-sidebar">
            <div class="tokaya-node-sidebar-topbox">
                <div class="tokaya-node-sidebar-profile">
                    <img class="tokaya-comment-avatar" src="{{ user.avatar }}">
                    <a href="/profile">{{ user.username }}</a>
                </div>
                <div class="tokaya-node-sidebar-post">
                    <a style="font-size: 12px;" href="{{ url_for('.add_topic') }}">创建新主题</a>
                </div>
            </div>
            <div class="tokaya-node-sidebar-ad">
                广告位招租
            </div>
        </div>
    </div>
{% endblock %}

templates/todo_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>todo edit</title>
</head>
<body>
    <div>
        <!-- action="/todo/update/{{todo.id}}" -->
        <form action="{{ url_for('.update', id=todo.id) }}" method="post">
            <input type="text" name="task" value="{{ todo.task }}">
            <button>更新</button>
        </form>
    </div>
</body>
</html>

templates/todo_index.html
{% extends "base.html" %}
{% block head %}
  {{ super() }}
  <link rel="stylesheet" href="/static/css/todo_index.css">
{% endblock %}
{% block title %}主页{% endblock %}
{% block content %}
<div class="todo-add">
    <form action="{{ url_for('.add') }}" method="post">
        <textarea type="text" name="task" placeholder="输入 todo"></textarea>
        <button>Add</button>
    </form>
</div>
{% for todo in todo_list %}
<div class="todo-cell">
    <div class="todo-time">
        {{ todo.created_time }}
    </div>
    <div class="todo-task">
        {{ todo.task }}
        <input class="todo-checkbox" type="checkbox">
    </div>
    <div class="todo-edit">
        <a class="todo-edit-icon" href="{{ url_for('.edit', id=todo.id) }}">
            <img src="/static/img/edit.gif" title="编辑">
        </a>
        <a class="todo-edit-icon" href="{{ url_for('.delete', id=todo.id) }}">
            <img src="/static/img/delete.png" title="删除">
        </a>
    </div>
</div>
{% endfor %}
{% endblock %}

templates/topic_add.html
{% extends "base.html" %}
{% block head %}
  {{ super() }}
  <link rel="stylesheet" href="/static/css/topic_add.css">
{% endblock %}
{% block title %}主页{% endblock %}
{% block content %}
<div class="tokaya-blog">
    <form action="{{ url_for('topic.add') }}" method="post">
        <input type="text" name="title" placeholder="帖子名字">
        <button>发表</button>
        <a href="{{ url_for('.show', id=1) }}">取消编辑</a>
        <div class="tokaya-blog-edit">
            <textarea name="content" placeholder="帖子内容"></textarea>
        </div>
        <select class="select-node font-size-16" name="node_id">
            {% for n in node_list%}
                <option value ="{{ n.id }}">{{ n.name }}</option>
            {% endfor %}
        </select>
    </form>
</div>

{% endblock %}

templates/topic_index.html
{% extends "base.html" %}
{% block head %}
  {{ super() }}
  <style type="text/css">
    p {
        background: red;
    }
  </style>
{% endblock %}
{% block title %}主页{% endblock %}
{% block content %}
    <div>
        <form action="{{ url_for('.add') }}" method="post">
            <div class="">
                <input type="text" name="title" placeholder="输入 title">
            </div>
            <div class="">
                <textarea name="content" placeholder="输入 content"></textarea>
            </div>
            <div class="">
                <button>Post Topic</button>
            </div>
        </form>
    </div>

    {% for m in topic_list %}
    <div>
        <a href="{{ url_for('.edit', id=m.id) }}">修改</a>
        <a href="{{ url_for('.delete', id=m.id) }}">删除</a>
        <h1> {{ m.title }} </h1>
        <div class="">
            {{ m.content }}
        </div>
    </div>
{% endfor %}
{% endblock %}